### ISSUE TITLE
Fix round trip test for float values

### ISSUE THREAD

**Issue by Armanbqt** [amzn/ion-go#42] opened 2020-05-22 21:39 UTC
For different values of type Float, round trip tests fail.
Fix for this issue should result in removing float related tests in roundtrip skip lists in integration_test.go.

**Comment by matthewh-BQ** [comment] 2020-06-12 19:01
@zslayton : Can we close this bucket issue for floats?

Remaining issues are:

- Equality of NaN. Deep Equals, as intended, does not consider two NaN's as equal. Integration tests will be expanded to handle cases such as these, but this more of a testing "problem" than an issue with Ion.

- Signed zeroes. Issue #68

**Comment by Armanbqt** [comment] 2020-06-12 19:21
Improving equivalency check in test is going to be done in #70

**Comment by zslayton** [comment] 2020-06-16 12:32
Closing in favor of #68 and #70.

**Closed by zslayton** 2020-06-16 12:32 UTC
Labels: S, bug
